In [1]:
# set up
import os
import warnings
import numpy as np
import pandas as pd
import functools as func
import functions_v2 as f
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('white')
home_path = "C:\\Users\joche\FIM Kernkompetenzzentrum\Projekt VIdES - Dokumente\General\\07_Arbeitsordner\\04_Ergebnisse\\20220920_Ergebnisse_4_Wochen"
os.chdir(home_path)

before changing to a use case folder, always make you switch to ``home_path`` first (and then go down one level by selecting the desired use case). This way, you can switch to any use case from **any** directory.

In [2]:
os.chdir(home_path)
os.chdir('Base_Case')

now we are in **Base_Case**. We hand over the current directory path with ``os.getcwd()`` to the functions. They only operate in and give results for the selected use case.

#### Notice:
To properly calculate results for a use case, all month-folders need to be unzipped.

#### KPI 1: Average price
---
To calculate the average price at each time step, there are four functions for the respective levels. At each level, for each month (here: 4) all relevant csv.-files are read in.
- f.avg_p_germany() -> 1 * 4 files
- f.avg_p_regions() -> 6 * 4 files
- f.avg_p_ecs() -> 36 * 4 files
- f.avg_p_houses() -> 1481 * 4 files
- f.avg_p_members() -> nr. depends on use case * 4 files

In [11]:
os.chdir(home_path)
os.chdir('Use_Case_2')

In [3]:
f.avg_p_regions(os.getcwd())

,slot,region1_avg trade rate [ct./kWh],region1_total trade volume [EURO ct.],region2_avg trade rate [ct./kWh],region2_total trade volume [EURO ct.],region3_avg trade rate [ct./kWh],region3_total trade volume [EURO ct.],region4_avg trade rate [ct./kWh],region4_total trade volume [EURO ct.],region5_avg trade rate [ct./kWh],region5_total trade volume [EURO ct.],region6_avg trade rate [ct./kWh],region6_total trade volume [EURO ct.]
0,2030-01-01T00:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
1,2030-01-01T01:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
2,2030-01-01T02:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
3,2030-01-01T03:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
4,2030-01-01T04:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2030-10-07T19:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
164,2030-10-07T20:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
165,2030-10-07T21:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
166,2030-10-07T22:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0
167,2030-10-07T23:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
f.avg_p_ecs(os.getcwd())

,slot,region_1_ec0_avg trade rate [ct./kWh],region_1_ec0_total trade volume [EURO ct.],region_1_ec1_avg trade rate [ct./kWh],region_1_ec1_total trade volume [EURO ct.],region_1_ec2_avg trade rate [ct./kWh],region_1_ec2_total trade volume [EURO ct.],region_1_ec3_avg trade rate [ct./kWh],region_1_ec3_total trade volume [EURO ct.],region_1_ec4_avg trade rate [ct./kWh],...,region_6_ec1_avg trade rate [ct./kWh],region_6_ec1_total trade volume [EURO ct.],region_6_ec2_avg trade rate [ct./kWh],region_6_ec2_total trade volume [EURO ct.],region_6_ec3_avg trade rate [ct./kWh],region_6_ec3_total trade volume [EURO ct.],region_6_ec4_avg trade rate [ct./kWh],region_6_ec4_total trade volume [EURO ct.],region_6_ec5_avg trade rate [ct./kWh],region_6_ec5_total trade volume [EURO ct.]
0,2030-01-01T00:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2030-01-01T01:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2030-01-01T02:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2030-01-01T03:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2030-01-01T04:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2030-10-07T19:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
164,2030-10-07T20:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
165,2030-10-07T21:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
166,2030-10-07T22:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
167,2030-10-07T23:00:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
f.avg_p_houses(os.getcwd())

In [3]:
f.avg_p_members(os.getcwd())

,slot,member_region_1_ec0_house_wind_avg trade rate [ct./kWh],member_region_1_ec0_house_wind_total trade volume [EURO ct.],member_region_1_ec1_house_0_avg trade rate [ct./kWh],member_region_1_ec1_house_0_total trade volume [EURO ct.],member_region_1_ec1_house_1_avg trade rate [ct./kWh],member_region_1_ec1_house_1_total trade volume [EURO ct.],member_region_1_ec1_house_10_avg trade rate [ct./kWh],member_region_1_ec1_house_10_total trade volume [EURO ct.],member_region_1_ec1_house_11_avg trade rate [ct./kWh],...,member_region_6_ec4_house_6_avg trade rate [ct./kWh],member_region_6_ec4_house_6_total trade volume [EURO ct.],member_region_6_ec4_house_7_avg trade rate [ct./kWh],member_region_6_ec4_house_7_total trade volume [EURO ct.],member_region_6_ec4_house_8_avg trade rate [ct./kWh],member_region_6_ec4_house_8_total trade volume [EURO ct.],member_region_6_ec4_house_9_avg trade rate [ct./kWh],member_region_6_ec4_house_9_total trade volume [EURO ct.],member_region_6_ec5_house_industry_avg trade rate [ct./kWh],member_region_6_ec5_house_industry_total trade volume [EURO ct.]
0,2030-01-01T00:00:00+00:00,12.88,1624.684313,28.18,17.125925,27.2813,16.689039,26.28,18.578208,28.4619,...,28.1832,128.310459,29.1698,17.253152,28.3761,119.968843,29.28,32.161152,23.03,1490.391843
1,2030-01-01T01:00:00+00:00,12.88,1566.642620,28.18,17.140955,27.2855,17.069398,26.28,17.505984,28.4141,...,28.2392,186.764163,29.1434,20.687470,28.3801,118.035174,25.68,26.672960,23.03,1445.690872
2,2030-01-01T02:00:00+00:00,12.88,1536.891232,28.18,18.478565,27.2243,18.178244,26.28,18.711360,28.4377,...,28.1327,130.663960,24.9271,17.780965,28.3787,118.275530,25.68,27.111232,23.03,1471.131523
3,2030-01-01T03:00:00+00:00,12.88,1538.699925,24.08,16.265237,27.2550,18.559634,26.28,17.344800,28.4692,...,28.1302,130.499440,24.9016,17.707469,28.3266,142.663067,25.68,49.613760,23.03,1490.908524
4,2030-01-01T04:00:00+00:00,12.88,1584.040737,24.08,14.049877,27.2565,16.024750,26.28,31.795296,28.4716,...,27.8990,146.513739,24.8760,33.113017,28.3299,140.447819,25.68,47.764800,23.03,1500.803298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2030-10-07T19:00:00+00:00,12.88,2972.696765,32.28,38.933984,33.4836,43.726038,32.48,67.211947,33.4836,...,33.4836,132.790760,33.4808,14.794920,33.3996,131.227028,32.88,35.773440,28.13,1705.931075
164,2030-10-07T20:00:00+00:00,12.88,2887.670212,32.28,35.749024,32.2713,38.431093,32.48,44.709803,33.4836,...,33.4836,130.765105,33.1059,13.284553,33.3930,134.749875,32.88,39.587520,28.13,1687.885541
165,2030-10-07T21:00:00+00:00,12.88,2765.065831,32.28,29.086432,32.0797,31.136768,32.48,47.386155,33.3947,...,33.4836,130.007025,33.1480,12.497013,33.3659,153.803524,32.88,58.789440,28.13,1698.193244
166,2030-10-07T22:00:00+00:00,12.88,2749.766260,32.28,34.113504,32.1021,35.925156,32.48,50.305024,33.4175,...,33.2179,127.786161,33.1560,11.472786,33.3681,151.511780,32.88,56.834176,28.13,1675.761823
167,2030-10-07T23:00:00+00:00,12.88,2652.697530,32.28,40.784704,32.1144,42.570595,29.38,24.945579,33.3981,...,33.1885,128.379236,29.5899,11.212375,33.3822,140.529439,29.28,41.195008,28.13,1705.028474

#### KPI 2: Total costs
---
To calculate the total costs for all months (here: 4), there is one function ``f.tot_cost()`` which returns a dictionary ``d`` with the levels as keys:
- d['germany']
- d['mm']
- d['region']
- d['ec']
- d['house']
- d['asset']

In [9]:
d = f.tot_cost(os.getcwd())
d.keys()

dict_keys(['germany', 'mm', 'region', 'ec', 'house', 'asset'])

In [5]:
d['region']

          name      total
1150  Region_1  21814.745
1351  Region_2  27233.231
1748  Region_3  17058.481
1889  Region_4  15803.935
2067  Region_5  13117.304
2254  Region_6  14968.703

In [10]:
d['house']

                             name      total
1152      Region_1_EC0_house_Wind  -6837.027
1154         Region_1_EC1_house_0    175.693
1155         Region_1_EC1_house_1    188.699
1156        Region_1_EC1_house_10    194.743
1157        Region_1_EC1_house_11    247.692
...                           ...        ...
2342         Region_6_EC4_house_6    905.460
2343         Region_6_EC4_house_7    128.407
2344         Region_6_EC4_house_8    889.988
2345         Region_6_EC4_house_9    231.063
2347  Region_6_EC5_house_Industry  13220.766

[553 rows x 2 columns]

#### KPI 3: Share Renewables
---
Calculates the share of grey energy, i.e. energy procured from the market. For the grey energy (the current German electricity mix), we need to define a share renewables.

Currently, a value of zero means that no grey energy is used, i.e. the entity consumes 100% renewable. A value of one means that the entity consumes 100% grey energy (electricity mix).

##### ATTENTION: Very long runtime
When needing to download all -trades.csv files, the function takes ~50min (!!) to complete.

In [3]:
os.chdir(home_path)
os.chdir('Base_Case')

In [4]:
f.share_renewables(os.getcwd())

,region-1-ec0-house-wind,region-1-ec0-house-wind_region-1-id-1-wind-feedin,region-1-ec1-house-0,region-1-ec1-house-1,region-1-ec1-house-10,region-1-ec1-house-11,region-1-ec1-house-12,region-1-ec1-house-13,region-1-ec1-house-14,region-1-ec1-house-15,...,region-6-ec4-house-5_region-6-id-487-hh-1-household-electric-load,region-6-ec4-house-6_region-6-id-79-heatpump-loadprofile,region-6-ec4-house-6_region-6-id-488-hh-1-household-electric-load,region-6-ec4-house-7_region-6-id-489-hh-1-household-electric-load,region-6-ec4-house-7_id-7-ev-non-commuter,region-6-ec4-house-8_region-6-id-511-hh-2-household-electric-load,region-6-ec4-house-8_region-6-id-78-heatpump-loadprofile,region-6-ec4-house-9_region-6-id-512-hh-2-household-electric-load,region-6-ec5-house-industry,region-6-industry-electric-load
2030-01-01T00:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T01:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T02:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T03:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T04:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030-10-07T19:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T20:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T21:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T22:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T23:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

... to this for all use cases ...

In [7]:
os.chdir(home_path)
os.chdir('Use_Case_2')

In [ ]:
f.share_renewables(os.getcwd())