In [4]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [5]:
# read in hourly capacity factors from excel
hourly_cap_factors_xlsx = pd.read_excel("PV_hourly_capacity.xlsx")
pd.options.display.float_format = '{:,.4f}'.format
hourly_factors = hourly_cap_factors_xlsx.rename(columns={"Capacity factor": "capacity_factor"})
hourly_factors

                Datetime  capacity_factor
0    2019-01-01 00:00:00           0.0000
1    2019-01-01 01:00:00           0.0000
2    2019-01-01 02:00:00           0.0000
3    2019-01-01 03:00:00           0.0000
4    2019-01-01 04:00:00           0.0000
...                  ...              ...
8755 2019-12-31 19:00:00           0.0000
8756 2019-12-31 20:00:00           0.0000
8757 2019-12-31 21:00:00           0.0000
8758 2019-12-31 22:00:00           0.0000
8759 2019-12-31 23:00:00           0.0000

[8760 rows x 2 columns]

In [17]:
# for each row, add three empty ones
empty_rows = 4
hourly_factors.index = range(0, empty_rows*len(hourly_factors), empty_rows)
df = hourly_factors.reindex(index=range(empty_rows*len(hourly_factors)))
# df

In [16]:
# generate 15min intervall series
start_date = datetime(2019,1,1)
quarter_hourly = [start_date + timedelta(minutes=15*x) for x in range(0,35040)]
quarter_hourly_list = [x.strftime('%Y-%m-%d %H:%M') for x in quarter_hourly]
# generate dataframe
quarter_hourly_list = pd.DataFrame(quarter_hourly_list, columns=['datetime'])
#quarter_hourly_list

In [33]:
# insert quarter-hourly list into df
df['datetime'] = quarter_hourly_list['datetime']
df_new = df[['datetime', 'capacity_factor']]
df_new = df_new.rename({'capacity_factor' : 'hourly_capacity_factor'}, axis='columns')
# df_new

In [39]:
# interpolate hourly to quarter-hourly values: linear interpolation
# since factors represent *hourly* capacity, a quarter hour only yields 1/4 the power
df_quarterly = df_new.interpolate(method='linear')
df_quarterly = df_quarterly.assign(quarterly_capacity_factor = lambda x: (x['hourly_capacity_factor'] / 4))
df_quarterly = df_quarterly[['datetime', 'quarterly_capacity_factor']]
df_quarterly.head(10)

           datetime  quarterly_capacity_factor
0  2019-01-01 00:00                     0.0000
1  2019-01-01 00:15                     0.0000
2  2019-01-01 00:30                     0.0000
3  2019-01-01 00:45                     0.0000
4  2019-01-01 01:00                     0.0000
5  2019-01-01 01:15                     0.0000
6  2019-01-01 01:30                     0.0000
7  2019-01-01 01:45                     0.0000
8  2019-01-01 02:00                     0.0000
9  2019-01-01 02:15                     0.0000

In [40]:
# write to xlsx
df_quarterly.to_excel(r'C:\Users\joche\ProgrammingProjects\04 FIM-RC\PV_wind power simulation\PV_quarterly_capacity.xlsx', index=False, header=True)