In [142]:
# set up
import os
import warnings
import numpy as np
import pandas as pd
import functools as func
import functions_v2 as f
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('white')
home_path = "C:\\Users\mkaiser\FIM Kernkompetenzzentrum\Projekt VIdES - General\\07_Arbeitsordner\\04_Ergebnisse\\20220920_Ergebnisse_4_Wochen"
results = "C:\\Users\mkaiser\FIM Kernkompetenzzentrum\Projekt VIdES - General\\07_Arbeitsordner\\04_Ergebnisse\\20220920_Ergebnisse_4_Wochen\\results"
os.chdir(home_path)

before changing to a use case folder, always make you switch to ``home_path`` first (and then go down one level by selecting the desired use case). This way, you can switch to any use case from **any** directory.

In [3]:
case = "Base_Case"

os.chdir(home_path)
os.chdir(case)

now we are in **Base_Case**. We hand over the current directory path with ``os.getcwd()`` to the functions. They only operate in and give results for the selected use case.

#### Notice:
To properly calculate results for a use case, all month-folders need to be unzipped.

#### KPI 1: Average price
---
To calculate the average price at each time step, there are four functions for the respective levels. At each level, for each month (here: 4) all relevant csv.-files are read in.
- f.avg_p_germany() -> 1 * 4 files
- f.avg_p_regions() -> 6 * 4 files
- f.avg_p_ecs() -> 36 * 4 files
- f.avg_p_houses() -> 1481 * 4 files
- f.avg_p_members() -> nr. depends on use case * 4 files

In [9]:
print("regions")
kpi1_regions=f.avg_p_regions(os.getcwd())
kpi1_regions.to_excel(results + "\\" + case + "\\kpi_avg_price_regions.xlsx")

print("germany")
kpi1_germany=f.avg_p_germany(os.getcwd())
kpi1_germany.to_excel(results + "\\" + case + "\\kpi_avg_price_germany.xlsx")

print("ecs")
kpi1_ecs=f.avg_p_ecs(os.getcwd())
kpi1_ecs.to_excel(results + "\\" + case + "\\kpi_avg_price_ecs.xlsx")

print("houses")
kpi1_houses=f.avg_p_houses(os.getcwd())
kpi1_houses.to_excel(results + "\\" + case + "\\kpi_avg_price_houses.xlsx")

print("members")
kpi1_members=f.avg_p_members(os.getcwd())
kpi1_members.to_excel(results + "\\" + case + "\\kpi_avg_price_members.xlsx")

OSError: [Errno 22] Invalid argument

#### KPI 2: Total costs
---
To calculate the total costs for all months (here: 4), there is one function ``f.tot_cost()`` which returns a dictionary ``d`` with the levels as keys:
- d['germany']
- d['mm']
- d['region']
- d['ec']
- d['house']
- d['asset']

In [11]:
d = f.tot_cost(os.getcwd())
d.keys()

d['region'].to_excel(results + "\\" + case + "\\kpi2_total_cost_regions.xlsx")
d['germany'].to_excel(results + "\\" + case + "\\kpi2_total_cost_germany.xlsx")
d['mm'].to_excel(results + "\\" + case + "\\kpi2_total_cost_mm.xlsx")
d['ec'].to_excel(results + "\\" + case + "\\kpi2_total_cost_ecs.xlsx")
d['asset'].to_excel(results + "\\" + case + "\\kpi2_total_cost_asset.xlsx")
d['house'].to_excel(results + "\\" + case + "\\kpi2_total_cost_house.xlsx")

#### KPI 3: Share Renewables
---
Calculates the share of grey energy, i.e. energy procured from the market. For the grey energy (the current German electricity mix), we need to define a share renewables.

Currently, a value of zero means that no grey energy is used, i.e. the entity consumes 100% renewable. A value of one means that the entity consumes 100% grey energy (electricity mix).

##### ATTENTION: Very long runtime
When needing to download all -trades.csv files, the function takes ~50min (!!) to complete.

In [105]:
case = "use_Case_4"
os.chdir(home_path)
os.chdir(case)

In [4]:
f.share_renewables(os.getcwd())

,region-1-ec0-house-wind,region-1-ec0-house-wind_region-1-id-1-wind-feedin,region-1-ec1-house-0,region-1-ec1-house-1,region-1-ec1-house-10,region-1-ec1-house-11,region-1-ec1-house-12,region-1-ec1-house-13,region-1-ec1-house-14,region-1-ec1-house-15,...,region-6-ec4-house-5_region-6-id-487-hh-1-household-electric-load,region-6-ec4-house-6_region-6-id-79-heatpump-loadprofile,region-6-ec4-house-6_region-6-id-488-hh-1-household-electric-load,region-6-ec4-house-7_region-6-id-489-hh-1-household-electric-load,region-6-ec4-house-7_id-7-ev-non-commuter,region-6-ec4-house-8_region-6-id-511-hh-2-household-electric-load,region-6-ec4-house-8_region-6-id-78-heatpump-loadprofile,region-6-ec4-house-9_region-6-id-512-hh-2-household-electric-load,region-6-ec5-house-industry,region-6-industry-electric-load
2030-01-01T00:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T01:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T02:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T03:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-01-01T04:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030-10-07T19:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T20:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T21:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T22:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2030-10-07T23:00:00+00:00,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

... to this for all use cases ...

In [31]:
kpi3 = share_renewables(os.getcwd())
kpi3.to_excel(results + "\\" + case + "\\kpi3_share_renewables.xlsx")

0 /1148
1 /1148
2 /1148
3 /1148
4 /1148
5 /1148
6 /1148
7 /1148
8 /1148
9 /1148
10 /1148
11 /1148
12 /1148
13 /1148
14 /1148
15 /1148
16 /1148
17 /1148
18 /1148
19 /1148
20 /1148
21 /1148
22 /1148
23 /1148
24 /1148
25 /1148
26 /1148
27 /1148
28 /1148
29 /1148
30 /1148
31 /1148
32 /1148
33 /1148
34 /1148
35 /1148
36 /1148
37 /1148
38 /1148
39 /1148
40 /1148
41 /1148
42 /1148
43 /1148
44 /1148
45 /1148
46 /1148
47 /1148
48 /1148
49 /1148
50 /1148
51 /1148
52 /1148
53 /1148
54 /1148
55 /1148
56 /1148
57 /1148
58 /1148
59 /1148
60 /1148
61 /1148
62 /1148
63 /1148
64 /1148
65 /1148
66 /1148
67 /1148
68 /1148
69 /1148
70 /1148
71 /1148
72 /1148
73 /1148
74 /1148
75 /1148
76 /1148
77 /1148
78 /1148
79 /1148
80 /1148
81 /1148
82 /1148
83 /1148
84 /1148
85 /1148
86 /1148
87 /1148
88 /1148
89 /1148
90 /1148
91 /1148
92 /1148
93 /1148
94 /1148
95 /1148
96 /1148
97 /1148
98 /1148
99 /1148
100 /1148
101 /1148
102 /1148
103 /1148
104 /1148
105 /1148
106 /1148
107 /1148
108 /1148
109 /1148
110 /1148
111 /1148
112 /1148
113 /1148
114 /1148
115 /1148
116 /1148
117 /1148
118 /1148
119 /1148
120 /1148
121 /1148
122 /1148
123 /1148
124 /1148
125 /1148
126 /1148
127 /1148
128 /1148
129 /1148
130 /1148
131 /1148
132 /1148
133 /1148
134 /1148
135 /1148
136 /1148
137 /1148
138 /1148
139 /1148
140 /1148
141 /1148
142 /1148
143 /1148
144 /1148
145 /1148
146 /1148
147 /1148
148 /1148
149 /1148
150 /1148
151 /1148
152 /1148
153 /1148
154 /1148
155 /1148
156 /1148
157 /1148
158 /1148
159 /1148
160 /1148
161 /1148
162 /1148
163 /1148
164 /1148
165 /1148
166 /1148
167 /1148
168 /1148
169 /1148
170 /1148
171 /1148
172 /1148
173 /1148
174 /1148
175 /1148
176 /1148
177 /1148
178 /1148
179 /1148
180 /1148
181 /1148
182 /1148
183 /1148
184 /1148
185 /1148
186 /1148
187 /1148
188 /1148
189 /1148
190 /1148
191 /1148
192 /1148
193 /1148
194 /1148
195 /1148
196 /1148
197 /1148
198 /1148
199 /1148
200 /1148
201 /1148
202 /1148
203 /1148
204 /1148
205 /1148
206 /1148
207 /1148
208 /1148
209 /1148
210 /1148
211 /1148
212 /1148
213 /1148
214 /1148
215 /1148
216 /1148
217 /1148
218 /1148
219 /1148
220 /1148
221 /1148
222 /1148
223 /1148
224 /1148
225 /1148
226 /1148
227 /1148
228 /1148
229 /1148
230 /1148
231 /1148
232 /1148
233 /1148
234 /1148
235 /1148
236 /1148
237 /1148
238 /1148
239 /1148
240 /1148
241 /1148
242 /1148
243 /1148
244 /1148
245 /1148
246 /1148
247 /1148
248 /1148
249 /1148
250 /1148
251 /1148
252 /1148
253 /1148
254 /1148
255 /1148
256 /1148
257 /1148
258 /1148
259 /1148
260 /1148
261 /1148
262 /1148
263 /1148
264 /1148
265 /1148
266 /1148
267 /1148
268 /1148
269 /1148
270 /1148
271 /1148
272 /1148
273 /1148
274 /1148
275 /1148
276 /1148
277 /1148
278 /1148
279 /1148
280 /1148
281 /1148
282 /1148
283 /1148
284 /1148
285 /1148
286 /1148
287 /1148
288 /1148
289 /1148
290 /1148
291 /1148
292 /1148
293 /1148
294 /1148
295 /1148
296 /1148
297 /1148
298 /1148
299 /1148
300 /1148
301 /1148
302 /1148
303 /1148
304 /1148
305 /1148
306 /1148
307 /1148
308 /1148
309 /1148
310 /1148
311 /1148
312 /1148
313 /1148
314 /1148
315 /1148
316 /1148
317 /1148
318 /1148
319 /1148
320 /1148
321 /1148
322 /1148
323 /1148
324 /1148
325 /1148
326 /1148
327 /1148
328 /1148
329 /1148
330 /1148
331 /1148
332 /1148
333 /1148
334 /1148
335 /1148
336 /1148
337 /1148
338 /1148
339 /1148
340 /1148
341 /1148
342 /1148
343 /1148
344 /1148
345 /1148
346 /1148
347 /1148
348 /1148
349 /1148
350 /1148
351 /1148
352 /1148
353 /1148
354 /1148
355 /1148
356 /1148
357 /1148
358 /1148
359 /1148
360 /1148
361 /1148
362 /1148
363 /1148
364 /1148
365 /1148
366 /1148
367 /1148
368 /1148
369 /1148
370 /1148
371 /1148
372 /1148
373 /1148
374 /1148
375 /1148
376 /1148
377 /1148
378 /1148
379 /1148
380 /1148
381 /1148
382 /1148
383 /1148
384 /1148
385 /1148
386 /1148
387 /1148
388 /1148
389 /1148
390 /1148
391 /1148
392 /1148
393 /1148
394 /1148
395 /1148
396 /1148
397 /1148
398 /1148
399 /1148
400 /1148
401 /1148
402 /1148
403 /1148
404 /1148
405 /1148
406 /1148
407 /1148
408 /1148
409 /1148
410 /1148
411 /1148
412 /1148
413 /1148
414 /1148
415 /1148
416 /1148
417 /1148
418 /1148
419 /1148
420 /1148
421 /1148
422 /1148
423 /1148
424 /1148
425 /1148
426 /1148
427 /1148
428 /1148
429 /1148
430 /1148
431 /1148
432 /1148
433 /1148
434 /1148
435 /1148
436 /1148
437 /1148
438 /1148
439 /1148
440 /1148
441 /1148
442 /1148
443 /1148
444 /1148
445 /1148
446 /1148
447 /1148
448 /1148
449 /1148
450 /1148
451 /1148
452 /1148
453 /1148
454 /1148
455 /1148
456 /1148
457 /1148
458 /1148
459 /1148
460 /1148
461 /1148
462 /1148
463 /1148
464 /1148
465 /1148
466 /1148
467 /1148
468 /1148
469 /1148
470 /1148
471 /1148
472 /1148
473 /1148
474 /1148
475 /1148
476 /1148
477 /1148
478 /1148
479 /1148
480 /1148
481 /1148
482 /1148
483 /1148
484 /1148
485 /1148
486 /1148
487 /1148
488 /1148
489 /1148
490 /1148
491 /1148
492 /1148
493 /1148
494 /1148
495 /1148
496 /1148
497 /1148
498 /1148
499 /1148
500 /1148
501 /1148
502 /1148
503 /1148
504 /1148
505 /1148
506 /1148
507 /1148
508 /1148
509 /1148
510 /1148
511 /1148
512 /1148
513 /1148
514 /1148
515 /1148
516 /1148
517 /1148
518 /1148
519 /1148
520 /1148
521 /1148
522 /1148
523 /1148
524 /1148
525 /1148
526 /1148
527 /1148
528 /1148
529 /1148
530 /1148
531 /1148
532 /1148
533 /1148
534 /1148
535 /1148
536 /1148
537 /1148
538 /1148
539 /1148
540 /1148
541 /1148
542 /1148
543 /1148
544 /1148
545 /1148
546 /1148
547 /1148
548 /1148
549 /1148
550 /1148
551 /1148
552 /1148
553 /1148
554 /1148
555 /1148
556 /1148
557 /1148
558 /1148
559 /1148
560 /1148
561 /1148
562 /1148
563 /1148
564 /1148
565 /1148
566 /1148
567 /1148
568 /1148
569 /1148
570 /1148
571 /1148
572 /1148
573 /1148
574 /1148
575 /1148
576 /1148
577 /1148
578 /1148
579 /1148
580 /1148
581 /1148
582 /1148
583 /1148
584 /1148
585 /1148
586 /1148
587 /1148
588 /1148
589 /1148
590 /1148
591 /1148
592 /1148
593 /1148
594 /1148
595 /1148
596 /1148
597 /1148
598 /1148
599 /1148
600 /1148
601 /1148
602 /1148
603 /1148
604 /1148
605 /1148
606 /1148
607 /1148
608 /1148
609 /1148
610 /1148
611 /1148
612 /1148
613 /1148
614 /1148
615 /1148
616 /1148
617 /1148
618 /1148
619 /1148
620 /1148
621 /1148
622 /1148
623 /1148
624 /1148
625 /1148

In [121]:

def share_renewable_helper(dict_out, df, p):
    # special case use case 4:
    if 'member' in p:
        p = p.replace('member', 'mm')
    # get children
    sellers = [i for i in df.seller.unique() if 'mm-' not in i and i != p]
    buyers = [i for i in df.buyer.unique() if 'mm-' not in i and i != p]
    with warnings.catch_warnings():
        warnings.simplefilter(action='ignore', category=FutureWarning)
        children = pd.Series(sellers + buyers).unique()
    df.set_index(['slot'], inplace=True)
    for slot, df_slot in df.groupby(level=0):
        if len(dict_out.keys()) < 1 or slot not in dict_out.keys():
            dict_out[slot] = dict()
        # p: parent entity name -> special case for highest level: Germany
        if 'germany' in p:
            p_to_cs = df_slot[df_slot.seller.str.contains(p) &
                              (~df_slot.buyer.str.contains(p))]['energy [kWh]'].sum()
            cs_to_p = df_slot[(~df_slot.seller.str.contains(p)) &
                              (df_slot.buyer.str.contains(p))]['energy [kWh]'].sum()
            net_p_to_cs = p_to_cs - cs_to_p
            p_share_grey_electricity = net_p_to_cs / p_to_cs if net_p_to_cs > 0 else 0
            dict_out[slot][p] = p_share_grey_electricity
        # c: children entity name
        for c in children:
            # net energy child bought from parent
            p_to_c = df_slot[df_slot.seller.str.contains(p) &
                             (df_slot.buyer.str.contains(c))]['energy [kWh]'].sum()
            c_to_p = df_slot[df_slot.seller.str.contains(c) &
                             (df_slot.buyer.str.contains(p))]['energy [kWh]'].sum()
            net_p_to_c = p_to_c - c_to_p
            # net energy child bought from other children
            cs_to_c = df_slot[(~df_slot.seller.str.contains(p)) &
                              (~df_slot.seller.str.contains(c)) &
                              (df_slot.buyer.str.contains(c))]['energy [kWh]'].sum()
            c_to_cs = df_slot[(df_slot.seller.str.contains(c)) &
                              (~df_slot.buyer.str.contains(p)) &
                              (~df_slot.buyer.str.contains(c))]['energy [kWh]'].sum()
            net_cs_to_c = cs_to_c - c_to_cs
            # children's share grey electricity
            if net_p_to_c > 0 and net_cs_to_c <= 0:
                c_share_grey_electricity = 1 if p not in dict_out[slot].keys() else dict_out[slot][p]
            elif net_p_to_c > 0 and net_cs_to_c > 0:
                p_share_grey_electricity = 1 if p not in dict_out[slot].keys() else dict_out[slot][p]
                c_share_grey_electricity = p_share_grey_electricity * (net_p_to_c / (net_p_to_c + net_cs_to_c))
            else:
                c_share_grey_electricity = 0
            # prevent overwriting of assets that are used in multiple houses (e.g. ev-non-commuter)
            c = c if 'id' not in c else p + '_' + c
            dict_out[slot][c] = c_share_grey_electricity

    return dict_out


def share_renewables(use_case_home_path):
    dict_out = dict()
    # get all relevant filepaths
    all_filepaths, all_filenames = [], []
    for root, dir, file in os.walk(top=use_case_home_path, topdown=True):
        all_filepaths += [os.path.join(root, f) for f in file if 'trades.csv' in f]
        all_filenames += [f for f in file if 'trades.csv' in f]
    # for each agent, construct subset_df and hand over to share_renewables_helper
    nr_months, l = all_filenames.count(all_filenames[0]), len(all_filenames)
    for i in range(int(l / nr_months)):
        print(i, "/1148")
        agent_dfs = []
        agent_all_filepaths = all_filepaths[i::int(l / nr_months)]
        for f in agent_all_filepaths:
            df = pd.read_csv(f).drop(['creation_time', 'matching_requirements', 'rate [ct./kWh]'], axis=1)
            df.seller = [i.lower().replace('_', '-') for i in df.seller]
            df.buyer = [i.lower().replace('_', '-') for i in df.buyer]
            agent_dfs.append(df)
        agent_name = agent_all_filepaths[0].split('\\')[-1].split('-trades.csv')[0]
        dict_out = share_renewable_helper(dict_out, pd.concat(agent_dfs).sort_values(by='slot').reset_index(drop=True),
                                          agent_name)

    return pd.DataFrame.from_dict(dict_out, orient='index')

#### KPI 4: Trade-Volume 
---
Calculates the trade volume within the market levels, i.e. energy traded between households within one EC.

In [198]:
os.chdir(home_path)
os.chdir('Use_Case_2/')
use_case = 2
use_case_home_path = os.getcwd()

In [199]:
# obtain all months' time slots from .json files and combine them to index
json_filepaths, timeslots = [], []
for root, dir, file in os.walk(top=use_case_home_path, topdown=True):
    json_filepaths += [os.path.join(root, f) for f in file if 'price_energy_day.json' in f]
for j in json_filepaths:
    df = pd.read_json(j)
    timeslots += [df['Germany']['price-energy-day'][i][0]['time'] for i in range(len(df['Germany']['price-energy-day']))]
timeslots.sort()
df_out = pd.DataFrame(index=timeslots)

In [200]:
# get all relevant filepaths
all_filepaths, all_filenames = [], []
for root, dir, file in os.walk(top=use_case_home_path, topdown=True):
    all_filepaths += [os.path.join(root, f) for f in file if 'trades.csv' in f]
    all_filenames += [f for f in file if 'trades.csv' in f]
relevant_filepaths, irrelevant_filepaths = f.share_renewables_necessary_files(all_filepaths, use_case)
nr_months, l = all_filenames.count(all_filenames[0]), len(relevant_filepaths)

In [201]:
# get all relevant filepaths
all_filepaths, all_filenames = [], []
for root, dir, file in os.walk(top=use_case_home_path, topdown=True):
    all_filepaths += [os.path.join(root, f) for f in file if 'trades.csv' in f]
    all_filenames += [f for f in file if 'trades.csv' in f]
relevant_filepaths, irrelevant_filepaths = f.share_renewables_necessary_files(all_filepaths, use_case)
nr_months, l = all_filenames.count(all_filenames[0]), len(relevant_filepaths)

In [221]:
# filter all filepaths by nr. 8 in relevant_filepaths -> nr. 8 is R1ec0

#Region 1: 9 - 12 (EC1 - EC4)
#Region 2: 104 - 107 (EC1 - EC4)
#Region 3: 283 - 286 (EC1 - EC4)
#Region 4: 348 - 351 (EC1 - EC4)
#Region 5: 427 - 430 (EC1 - EC4)
#Region 6: 505 - 508 (EC1 - EC4)

#relevant_filepaths[508::597]



list_regions = [[9,10,11,12],[104,105,106,107],[283,283,285,286],[348,349,350,351],[427,428,429,450],[505,506,507,508]]

for z in range (0,6):
    print(z)
    for t in list_regions [z]:
        z = z+1
        print(t)
        globals()['tradevol_EC_R%s' % z] = trade_vol_region(relevant_filepaths, 9, 13, df_out).reset_index().rename({"index":"date"},axis=1)
        globals()['tradevol_EC_R%s' % z]["date"] = pd.to_datetime(globals()['tradevol_EC_R%s' % z]["date"])
        globals()['tradevol_EC_R%s' % z][["Year","Monath","Day", "Hour"]] = [[x.year,x.month,x.day,x.hour] for x in globals()['tradevol_EC_R%s' % z]["date"]]
    
    #print(globals()['tradevol_EC_R%s' % z])


'''
region = "Region_1"



if region == "Region_1":
    tradevol_EC_R1 = trade_vol_region(relevant_filepaths, 9, 13, df_out).reset_index().rename({"index":"date"},axis=1)
    tradevol_EC_R1["date"] = pd.to_datetime(tradevol_EC_R1["date"])
    tradevol_EC_R1[["Year","Monath","Day", "Hour"]] = [[x.year,x.month,x.day,x.hour] for x in tradevol_EC_R1["date"]]
elif region == "Region_2":
    tradevol_EC_R2 = trade_vol_region(relevant_filepaths, 104, 107, df_out).reset_index().rename({"index":"date"},axis=1)
elif region == "Region_3":
    tradevol_EC_R3 = trade_vol_region(relevant_filepaths, 283, 286, df_out).reset_index().rename({"index":"date"},axis=1)
elif region == "Region_4":
    tradevol_EC_R4 = trade_vol_region(relevant_filepaths, 348, 351, df_out).reset_index().rename({"index":"date"},axis=1)
elif region == "Region_5":
    tradevol_EC_R5 = trade_vol_region(relevant_filepaths, 427, 430, df_out).reset_index().rename({"index":"date"},axis=1)
elif region == "Region_6":
    tradevol_EC_R6 = trade_vol_region(relevant_filepaths, 505, 508, df_out).reset_index().rename({"index":"date"},axis=1)



tradevol_EC_R1
'''

0
9
10
11
12
1
104
105
106
107
2
283
283
285
286
3
348
349
350
351
4
427
428
429
450
5
505
506
507
508

'\nregion = "Region_1"\n\n\n\nif region == "Region_1":\n    tradevol_EC_R1 = trade_vol_region(relevant_filepaths, 9, 13, df_out).reset_index().rename({"index":"date"},axis=1)\n    tradevol_EC_R1["date"] = pd.to_datetime(tradevol_EC_R1["date"])\n    tradevol_EC_R1[["Year","Monath","Day", "Hour"]] = [[x.year,x.month,x.day,x.hour] for x in tradevol_EC_R1["date"]]\nelif region == "Region_2":\n    tradevol_EC_R2 = trade_vol_region(relevant_filepaths, 104, 107, df_out).reset_index().rename({"index":"date"},axis=1)\nelif region == "Region_3":\n    tradevol_EC_R3 = trade_vol_region(relevant_filepaths, 283, 286, df_out).reset_index().rename({"index":"date"},axis=1)\nelif region == "Region_4":\n    tradevol_EC_R4 = trade_vol_region(relevant_filepaths, 348, 351, df_out).reset_index().rename({"index":"date"},axis=1)\nelif region == "Region_5":\n    tradevol_EC_R5 = trade_vol_region(relevant_filepaths, 427, 430, df_out).reset_index().rename({"index":"date"},axis=1)\nelif region == "Region_6":\n    tradevol_EC_R6 = trade_vol_region(relevant_filepaths, 505, 508, df_out).reset_index().rename({"index":"date"},axis=1)\n\n\n\ntradevol_EC_R1\n'

In [218]:
tradevol_EC_R1

,date,EC1,EC2,EC3,EC4,Year,Monath,Day,Hour
0,2030-01-01 00:00:00,0.303867,0.297111,0.302178,0.373378,2030,1,1,0
1,2030-01-01 01:00:00,0.304133,0.332222,0.311156,0.356596,2030,1,1,1
2,2030-01-01 02:00:00,0.327867,0.343067,0.331667,0.357320,2030,1,1,2
3,2030-01-01 03:00:00,0.337733,0.347778,0.340244,0.365791,2030,1,1,3
4,2030-01-01 04:00:00,0.291733,0.539467,0.353667,0.424600,2030,1,1,4
...,...,...,...,...,...,...,...,...,...
667,2030-10-07 19:00:00,0.603067,0.315067,0.531067,0.529733,2030,10,7,19
668,2030-10-07 20:00:00,0.553733,0.290533,0.487933,0.455613,2030,10,7,20
669,2030-10-07 21:00:00,0.450533,0.252667,0.401067,0.410880,2030,10,7,21
670,2030-10-07 22:00:00,0.528400,0.270711,0.463978,0.408564,2030,10,7,22
671,2030-10-07 23:00:00,0.631733,0.316178,0.552844,0.468631,2030,10,7,23

In [180]:
#Group by Day to get avg over all days
tradevol_EC_R1.groupby(["Year","Hour"])["EC1","EC2", "EC3", "EC4"].mean().reset_index()

C:\Users\mkaiser\AppData\Local\Temp\ipykernel_6876\2280491607.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  tradevol_EC_R1.groupby(["Year","Hour"])["EC1","EC2", "EC3", "EC4"].mean().reset_index()

    Year  Hour       EC1       EC2       EC3       EC4
0   2030     0  0.475390  0.358168  0.446085  0.467513
1   2030     1  0.450095  0.370019  0.430076  0.459183
2   2030     2  0.469248  0.349670  0.439353  0.451578
3   2030     3  0.417833  0.339243  0.398186  0.427250
4   2030     4  0.439090  0.364246  0.420379  0.469345
5   2030     5  0.496619  0.373629  0.465871  0.472664
6   2030     6  0.524671  0.394224  0.492060  0.496507
7   2030     7  0.465976  0.369614  0.441886  0.468989
8   2030     8  0.451143  0.338413  0.422960  0.459998
9   2030     9  0.470390  0.358600  0.442443  0.467645
10  2030    10  0.417929  0.331233  0.396255  0.437847
11  2030    11  0.408081  0.321859  0.386525  0.439070
12  2030    12  0.404848  0.325429  0.384993  0.435890
13  2030    13  0.384814  0.309481  0.365981  0.420830
14  2030    14  0.359786  0.292722  0.343020  0.413637
15  2030    15  0.382776  0.312668  0.365249  0.429443
16  2030    16  0.397095  0.327327  0.379653  0.459287
17  2030    17  0.453729  0.346427  0.426903  0.464368
18  2030    18  0.394929  0.311983  0.374192  0.445327
19  2030    19  0.395495  0.306625  0.373278  0.439333
20  2030    20  0.408686  0.311702  0.384440  0.431908
21  2030    21  0.427248  0.320384  0.400532  0.436337
22  2030    22  0.466890  0.338462  0.434783  0.462273
23  2030    23  0.449652  0.317617  0.416644  0.440392

In [206]:
tradevol_EC_R1 = trade_vol_region(relevant_filepaths, 9, 13, df_out).reset_index().rename({"index":"date"},axis=1)

In [204]:


def trade_vol_region(relevant_filepaths, lbound, ubound, df_out):
    df_volume = pd.DataFrame()
    for i in range (lbound,ubound):
        #print(i)
        #i = range(int(l / nr_months))[2]
        entity_monthly_dfs = []
        entity_monthly_filepaths = relevant_filepaths[i::int(l / nr_months)]
        # combine each entity's monthly data frames and hand them over to shares_renewable_helper for calculation
        for f in entity_monthly_filepaths:
            df_temp = pd.read_csv(f).drop(['creation_time', 'matching_requirements', 'rate [ct./kWh]'], axis=1)
            df_temp.seller = [i.lower().replace('_', '-') for i in df_temp.seller]
            df_temp.buyer = [i.lower().replace('_', '-') for i in df_temp.buyer]
            entity_monthly_dfs.append(df_temp)
        entity_name = entity_monthly_filepaths[0].split('\\')[-1].split('-trades.csv')[0]
        entity_df = pd.concat(entity_monthly_dfs).sort_values(by='slot').reset_index(drop=True)
        entity_df.set_index(['slot'], inplace=True)
        #R_entity_df = pd.concat([R_entity_df,entity_df])
        #print(entity_df)
        
        df = entity_df
        p = entity_name

        if 'member' in p:
            p = p.replace('member', 'mm')
        # get children
        sellers = [t for t in df.seller.unique() if 'mm-' not in t and t != p]
        buyers = [t for t in df.buyer.unique() if 'mm-' not in t and t != p]
        children = pd.Series([*sellers, *buyers]).unique()
        #print(children)

        import functions_v2 as f 
        df_volume_EC = pd.DataFrame()
        for j in range (0, len(children)):
            c = children[j]
            #print(f'c: {c}')
            p_to_c = f.share_renewable_df_grouper(df_out, df[(df.seller == p) & (df.buyer == c)][['energy [kWh]']])
            c_to_p = f.share_renewable_df_grouper(df_out, df[(df.seller == c) & (df.buyer == p)][['energy [kWh]']])
            net_p_to_c = p_to_c - c_to_p
            cs_to_c = f.share_renewable_df_grouper(df_out, df[(df.seller != p) & (df.seller != c) & (df.buyer == c)][
                ['energy [kWh]']])
            c_to_cs = f.share_renewable_df_grouper(df_out,
                                                df[(df.seller == c) & (df.buyer != p) & (df.buyer != c)][['energy [kWh]']])
            net_cs_to_c = cs_to_c - c_to_cs
            # prepare copy of df_out where calculations are made
            c_name = c if 'id' not in c else p + '_' + c
            df_out_copy = df_out.copy()
            df_out_copy[f'{c_name}_p_to_c'] = p_to_c
            df_out_copy[f'{c_name}_cs_to_c'] = cs_to_c
            #df_out_copy[f'{c_name}_net_cs_to_c'] = net_cs_to_c
            df_volume_EC = pd.concat([df_volume,df_out_copy], axis=1).mean(axis=1)
        df_volume = pd.concat([df_volume, df_volume_EC], axis =1)

    #df_volume = df_volume.to_frame().reset_index().rename({0:"EC1",0:"EC2",0:"EC3",0:"EC4"},axis=1)
    headers = ["EC1","EC2","EC3","EC4"]
    df_volume.columns = headers
    return df_volume

In [82]:
# Handover to helper function
df = R_entity_df
p = entity_name

In [83]:
if 'member' in p:
    p = p.replace('member', 'mm')
# get children
sellers = [i for i in df.seller.unique() if 'mm-' not in i and i != p]
buyers = [i for i in df.buyer.unique() if 'mm-' not in i and i != p]
children = pd.Series([*sellers, *buyers]).unique()
children

array(['region-1-ec1', 'region-1-ec1-house-14', 'region-1-ec1-house-16',
       'region-1-ec2-house-9', 'region-1-ec2-house-21',
       'region-1-ec2-house-4', 'region-1-ec1-house-17',
       'region-1-ec1-house-0', 'region-1-ec1-house-6',
       'region-1-ec1-house-7', 'region-1-ec1-house-12',
       'region-1-ec1-house-8', 'region-1-ec1-house-15',
       'region-1-ec1-house-11', 'region-1-ec1-house-1',
       'region-1-ec1-house-3', 'region-1-ec1-house-5',
       'region-1-ec1-house-9', 'region-1-ec1-house-20',
       'region-1-ec1-house-10', 'region-1-ec1-house-19',
       'region-1-ec1-house-4', 'region-1-ec1-house-18',
       'region-1-ec1-house-13', 'region-1-ec1-house-2',
       'region-1-ec2-house-0', 'region-1-ec2-house-11',
       'region-1-ec2-house-17', 'region-1-ec2-house-19',
       'region-1-ec2-house-12', 'region-1-ec2-house-15',
       'region-1-ec2-house-6', 'region-1-ec2-house-18',
       'region-1-ec2-house-8', 'region-1-ec2-house-13',
       'region-1-ec2-house-1', 'region-1-ec2-house-16',
       'region-1-ec2-house-14', 'region-1-ec2-house-10',
       'region-1-ec2-house-20', 'region-1-ec2-house-7',
       'region-1-ec2-house-3', 'region-1-ec2-house-2',
       'region-1-ec2-house-5'], dtype=object)

In [113]:
# select one child
df_volume = pd.DataFrame()
for i in range (0, len(children)):
    c = children[i]
    print(f'c: {c}')
    p_to_c = f.share_renewable_df_grouper(df_out, df[(df.seller == p) & (df.buyer == c)][['energy [kWh]']])
    c_to_p = f.share_renewable_df_grouper(df_out, df[(df.seller == c) & (df.buyer == p)][['energy [kWh]']])
    net_p_to_c = p_to_c - c_to_p
    cs_to_c = f.share_renewable_df_grouper(df_out, df[(df.seller != p) & (df.seller != c) & (df.buyer == c)][
        ['energy [kWh]']])
    c_to_cs = f.share_renewable_df_grouper(df_out,
                                        df[(df.seller == c) & (df.buyer != p) & (df.buyer != c)][['energy [kWh]']])
    net_cs_to_c = cs_to_c - c_to_cs
    # prepare copy of df_out where calculations are made
    c_name = c if 'id' not in c else p + '_' + c
    df_out_copy = df_out.copy()
    df_out_copy[f'{c_name}_p_to_c'] = p_to_c
    df_out_copy[f'{c_name}_cs_to_c'] = cs_to_c
    #df_out_copy[f'{c_name}_net_cs_to_c'] = net_cs_to_c
    df_volume = pd.concat([df_volume,df_out_copy], axis=1).sum(axis=1)

df_volume

c: region-1-ec1-house-14

AttributeError: 'str' object has no attribute 'share_renewable_df_grouper'

In [77]:
df_volume_date = df_volume.to_frame().reset_index().rename({"index":"date",0:"Energy"},axis=1)
df_volume_date["date"] = pd.to_datetime(df_volume_date["date"])
df_volume_date[["Year","Monath","Day", "Hour"]] = [[x.year,x.month,x.day,x.hour] for x in df_volume_date["date"]]
df_volume_date

                   date      Energy  Year  Monath  Day  Hour
0   2030-01-01 00:00:00  122.101285  2030       1    1     0
1   2030-01-01 01:00:00  128.843451  2030       1    1     1
2   2030-01-01 02:00:00  124.067821  2030       1    1     2
3   2030-01-01 03:00:00  124.143196  2030       1    1     3
4   2030-01-01 04:00:00  138.921040  2030       1    1     4
..                  ...         ...   ...     ...  ...   ...
667 2030-10-07 19:00:00  145.280383  2030      10    7    19
668 2030-10-07 20:00:00  132.680822  2030      10    7    20
669 2030-10-07 21:00:00  122.947690  2030      10    7    21
670 2030-10-07 22:00:00  131.032440  2030      10    7    22
671 2030-10-07 23:00:00  124.569399  2030      10    7    23

[672 rows x 6 columns]

In [86]:
x = df_volume_mm.groupby(["Year","Monath","Hour"])["Energy"].mean().reset_index()
x

    Year  Monath  Hour     Energy
0   2030       1     0  28.934231
1   2030       1     1  29.133844
2   2030       1     2  29.139458
3   2030       1     3  29.324745
4   2030       1     4  28.532900
..   ...     ...   ...        ...
91  2030      10    19  31.742547
92  2030      10    20  30.005506
93  2030      10    21  31.197530
94  2030      10    22  32.448688
95  2030      10    23  32.691753

[96 rows x 4 columns]

In [82]:
df_volume_mm.iloc[667,0].hour

19

In [31]:
print(c,p)


c_to_p

region-1-ec1-house-2 region-1-ec1

                  energy [kWh]
2030-01-01T00:00           0.0
2030-01-01T01:00           0.0
2030-01-01T02:00           0.0
2030-01-01T03:00           0.0
2030-01-01T04:00           0.0
...                        ...
2030-10-07T19:00           0.0
2030-10-07T20:00           0.0
2030-10-07T21:00           0.0
2030-10-07T22:00           0.0
2030-10-07T23:00           0.0

[672 rows x 1 columns]